name: build-images

on:
  schedule:
    - cron: '0 4 * * *' # everyday at 4am
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
        with:
          version: latest
          install: true
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build images
        run: |
          latest=1.8.12
          for version in "1.8.12" "2.1.0"; do
            docker build \
              --build-arg BRIDGE_VERSION="v${version}" \
              --tag syphr/proton-bridge:"${version}" \
              $(if [ "${version}" = "${latest}" ]; then echo "--tag syphr/proton-bridge:latest"; fi) \
              --platform linux/amd64,linux/arm64 \
              --push \
              .
          done
      - name: Cleanup
        run: rm -f ${HOME}/.docker/config.json
